config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
     resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end
  resources :order_items
  resources :comments
  resources :orders
  resources :food_items
  resources :categories
  get 'cart' => 'cart#show'
  get 'menu/index'
  devise_for :users
  root 'pages#home'
  get 'comments/index'
  get 'catering' => 'pages#catering'
  get 'info' => 'pages#info'
  get 'menu' => 'menu#index'
  get 'review' => 'comments#index'
  get 'search' => 'menu#search'
  get 'food_items' => 'food_items#index'
  get 'orders' => 'orders#index'
  #root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :food_item
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :title, :description, :price, presence: true
  validates :title, :uniqueness => true
  has_many :order_items
  belongs_to :category
  has_many :comments
  has_one_attached :image

  def image_url_present
    if image_url.present?
      image_url
    else
      "https://loremflickr.com/320/240/#{title}"
    end
  end
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def set_subtotal
    order_items.collect{|order_item| order_item.valid ? order_ite.unit_price * order_item.quantity : 0}.sum
  end
  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      food_item.price
    end
  end

  def total
    return unit_price * quantity
  end
  private
  def set_unit_price
    self[:unit_price] = unit_price
  end
  
  def set_total
    self[:total] = total * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/food_items_controller.rb
class API::V1::FoodItemsController < ApplicationController
  def index
    render json: FoodItem.all
  end

  def create
    food_item = FoodItem.create(food_item_params)
    render json: food_item
  end

  def destroy
    FoodItem.destroy(params[:id])
  end

  def update
    food_item = FoodItem.find(params[:id])
    food_item.update_attributes(food_item_params)
    render json: food_item
  end

  private

  def food_item_params
    params.require(:food_item).permit(:title, :description, :price, :category_id, :available, :catering, :featured)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: %i[ show edit update destroy ]
  # GET /food_items or /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1 or /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items or /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)
    @food_item.category = Category.find(params[:food_item][:category_id])
    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: "Food item was successfully created." }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1 or /food_items/1.json
  def update
    @food_item.category = Category.find(params[:food_item][:category_id])
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: "Food item was successfully updated." }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1 or /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: "Food item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_item_params
      params.require(:food_item).permit(:title, :description, :price, :image, :category_id, :available, :catering, :featured)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats
  def index
    @food_items = FoodItem.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]
    @food_items = FoodItem.all
    @cats = Category.all.where('title LIKE ?', "%#{query}%")
  end
  private
  def set_cats
    @cats = Category.all.where(display:true)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def index
    @orders = Order.all
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:subtotal, :total, :paid)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:pages, :home, :info]
  def home
    @page= 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="field">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="field">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <% default_cat = food_item.category.nil? ? Category.first.id : @food_item.category.id %>
  <div class="field">
    <%= form.label :category %>
    <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :title, default_cat) %>
  </div>


  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.title %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.available %></td>
        <td><%= food_item.catering %></td>
        <td><%= food_item.featured %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @food_item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @food_item.available %>
</p>

<p>
  <strong>Catering:</strong>
  <%= @food_item.catering %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @food_item.featured %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>