config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
     resources :food_items, only: [:index, :create, :destroy, :update]
    end
  end
  resources :order_items
  resources :comments
  resources :orders
  resources :food_items
  resources :categories
  get 'cart' => 'cart#show'
  get 'menu/index'
  devise_for :users
  root 'pages#home'
  get 'comments/index'
  get 'catering' => 'pages#catering'
  get 'info' => 'pages#info'
  get 'menu' => 'menu#index'
  get 'review' => 'comments#index'
  get 'search' => 'menu#search'
  get 'food_items' => 'food_items#index'
  get 'orders' => 'orders#index'
  #root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :food_item
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  validates :title, :description, :price, presence: true
  validates :title, :uniqueness => true
  has_many :order_items
  belongs_to :category
  has_many :comments
  has_one_attached :image

  def image_url_present
    if image_url.present?
      image_url
    else
      "https://loremflickr.com/320/240/#{title}"
    end
  end
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def set_subtotal
    order_items.collect{|order_item| order_item.valid ? order_ite.unit_price * order_item.quantity : 0}.sum
  end
  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total

  def unit_price
    if persisted?
      self[:unit_price]
    else
      food_item.price
    end
  end

  def total
    return unit_price * quantity
  end
  private
  def set_unit_price
    self[:unit_price] = unit_price
  end
  
  def set_total
    self[:total] = total * quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_cats
  def index
    @food_items = FoodItem.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]
    @food_items = FoodItem.all
    @cats = Category.all.where('title LIKE ?', "%#{query}%")
  end
  private
  def set_cats
    @cats = Category.all.where(display:true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_admin_pages.html.erb
<h5 class="link-container">
  <%= link_to "Food Items", food_item_path %>
</h5>
<h5 class="link-container">
  <%= link_to "Orders", orders_path %>
</h5>
</h5>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_pageLinks.html.erb
<div style = "color:white" class="col-2">


    <% if current_user %>
    <h5 class="link-container" style="color:white">
            <%= link_to "Home", root_path %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "Menu", menu_path %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "More Info", info_path %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "Customer Reviews", review_path %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "Log Out", destroy_user_session_path,  :method => :delete %>
            </h5>
             <% if current_user.admin %>
            <h5 class="link-container">
            <%= link_to "Food Items", "/food_items" %>
            </h5>
            <h5 class="link-container">
            <%= link_to "Cart", "/cart" %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "Orders", "/orders" %>
            </h5>
            <h5 class="link-container" style="color:white">
            <%= link_to "Categories", "/categories" %>
            </h5>
            
    <% end %>
        <% else %>
         <h5 class="link-container" style="color:white">
                <%= link_to "Sign up", new_user_registration_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "Sign In", new_user_session_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "Home", root_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "Menu", menu_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "More Info", info_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "Customer Reviews", review_path %>
            </h5>
            <h5 class="link-container" style="color:white">
                <%= link_to "Cart", "/cart" %>
            </div>


    <% end %>



</div>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text">
        Dinner Dash
    </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DinnerDash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: white">
   <div class="<%= @page %>-page">
        <div class="row page-container">
            <%= render 'layouts/pageLinks'%>
            <div class="col-8">
                <% unless @page == "home"%>
                <%= render 'layouts/title'%>
                <% end %>
                <%= yield %>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div style=""><h1>Welcome to the Dinner Dash</h1></div>

app/views/pages/info.html.erb
<div style="background:white" class="p-3">
<h1>More Information</h1>
<p>ARestaurants and food service industry leaders seek to achieve peak operational efficiency today while building the foundations for success in the future, too. With cloud-based solutions like restaurant point of sale (POS) and advanced table and reservations systems (TRS), along with a range of applications to serve a whole spectrum of activities, here are some of the challenges and goals Infor helps our customers address every day.
Restaurants and food service industry leaders seek to achieve peak operational efficiency today while building the foundations for success in the future, too. With cloud-based solutions like restaurant point of sale (POS) and advanced table and reservations systems (TRS), along with a range of applications to serve a whole spectrum of activities, here are some of the challenges and goals Infor helps our customers address every day.
Restaurants and food service industry leaders seek to achieve peak operational efficiency today while building the foundations for success in the future, too. With cloud-based solutions like restaurant point of sale (POS) and advanced table and reservations systems (TRS), along with a range of applications to serve a whole spectrum of activities, here are some of the challenges and goals Infor helps our customers address every day.</p>
</div>